# Generated by Django 3.1.7 on 2021-03-04 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=256, verbose_name='country')),
                ('state', models.CharField(max_length=256, verbose_name='state')),
                ('city', models.CharField(max_length=256, verbose_name='city')),
                ('cep', models.IntegerField(verbose_name='cep')),
                ('street', models.CharField(max_length=256, verbose_name='street')),
                ('houseNumber', models.PositiveIntegerField(verbose_name='houseNumber')),
                ('complement', models.CharField(max_length=256, null=True, verbose_name='complement')),
                ('cpf', models.IntegerField(verbose_name='cpf')),
                ('pis', models.IntegerField(verbose_name='pis')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
