# Generated by Django 3.1.7 on 2021-03-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_auto_20210304_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pis',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='pis'),
        ),
    ]
